name: docker
on: 
  push:
    branches:
      - "answer"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: patrickrainier/amongus-todo:${{ github.run_id }}
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: patrickrainier/amongus-todo:${{ github.run_id }}
          args: --file=Dockerfile          
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: patrickrainier
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: patrickrainier/amongus-todo:${{ github.run_id }} 